# Generated by Django 4.1.4 on 2023-01-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='CategoryDetail')),
            ],
            options={
                'verbose_name': 'Category Detail',
                'verbose_name_plural': 'Detail Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='categorysale',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('options', models.CharField(max_length=255, verbose_name='Options')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('cover', models.ImageField(upload_to='static/img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detailcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Spare',
                'verbose_name_plural': 'Spares',
            },
        ),
    ]
